variants:
- name: default
  context:
    criteriaCard:
      topic: images
      topicNumber: 1
      status: C
      criterium:
        number: 1
        title: Chaque image [porteuse d'information](#image-porteuse-d-information)
          a-t-elle une [alternative textuelle](#alternative-textuelle-image) ?
        tests:
          '1': Chaque image a-t-elle une [alternative textuelle](#alternative-textuelle-image) ?
          '2': Chaque [zone](#zone-d-une-image-reactive) a-t-elle une [alternative textuelle](#alternative-textuelle-image) ?
          '3': Chaque bouton de type image a-t-il une [alternative textuelle](#alternative-textuelle-image) ?
          '4': Chaque zone cliquable d'une image réactive côté serveur est-t-elle doublée d'un lien dans la page ?
          '5':
          - Chaque image vectorielle vérifie-t-elle ces conditions ?
          - La balise possède un attribut WAI-ARIA `role="img"`.
          - La balise a une [alternative textuelle](#alternative-textuelle-image).
- name: images-1
  context:
    attributeList:
      class: -checked
    criteriaCard:
      topic: images
      topicNumber: 1
      criterium:
        number: 2
        title: Chaque [image de décoration](#image-de-decoration) est-elle correctement ignorée par les technologies d'assistance ?
        tests:
          '1':
          - "Chaque image (balise) [de décoration](#image-de-decoration), sans [légende](#legende), vérifie-t-elle une de ces conditions ?"
          - "La balise possède un attribut alt vide (`alt=\"\"`) et est dépourvue de tout autre attribut permettant de fournir une [alternative textuelle](#alternative-textuelle-image)."
          - "La balise possède un attribut WAI-ARIA `aria-hidden=\"true\"` ou `role=\"presentation\"`."
- name: frames-1
  context:
    criteriaCard:
      topic: frames
      topicNumber: 2
      criterium:
        number: 1
        title: Chaque <strong>cadre</strong> a-t-il un titre de cadre ?
- name: frames-2
  context:
    criteriaCard:
      topic: frames
      topicNumber: 2
      status: NC
      criterium:
        number: 2
        title: Pour chaque <strong>cadre</strong> ayant un titre de cadre, ce <strong>titre de cadre</strong> est-il pertinent ?
